#!/bin/bash
# Copyright (C) 2019 Omar Castro <omar.castro.360@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


XRANDR_OUTPUT=$(xrandr)
ACTIVE_OUTPUTS=( $( awk '/[0-9]+x[0-9]+\+[0-9]+\+[0-9]+/{ print $1 }' <<< "$XRANDR_OUTPUT" ) )
MONITORS=( $( awk '( $2 == "connected" ){ print $1 }'  <<< "$XRANDR_OUTPUT" ) )
ACTIVE_MONITORS=( $( awk '/[0-9]+x[0-9]+\+[0-9]+\+[0-9]+/ && ( $2 == "connected" ){ print $1 }' <<< "$XRANDR_OUTPUT" ) )
NUM_MONITORS=${#MONITORS[@]}
TITLES=()
declare -A COMMANDS=()


addCommand(){
    TITLES+=("$1")
    COMMANDS[$1]="$2"
}

#addCommand "Cancel" "true"

for entry in "${MONITORS[@]}"; do
    addCommand "Layout: Only $entry" "set_xrandr_only $entry"
done

##
# Dual screen options
##
for entry_a in "${MONITORS[@]}"; do
    for entry_b in "${MONITORS[@]}"; do
        if [ $entry_a != $entry_b ]; then
            addCommand "Layout: Dual Screen $entry_a 🖵 🖵 $entry_b" "xrandr --output $entry_b --auto --output $entry_a --auto --left-of $entry_b"
        fi
    done
done


##
# Clone monitors
##
addCloneCommand(){
    if [ $1 != $2 ]; then
        addCommand "Layout: Clone Screen $1 & $2 🖵" "xrandr --output $1 --auto --output $2 --auto --same-as $1"
    fi
}
for ((idx_a = 0; idx_a < $NUM_MONITORS; ++idx_a)); do
    for ((idx_b = idx_a; idx_b < $NUM_MONITORS; ++idx_b)); do
        addCloneCommand ${MONITORS[$idx_a]} ${MONITORS[$idx_b]}
    done
done


##
# Night mode
##
addCommand "Night mode: ON (Set to manual)" "night_manual_on"
addCommand "Night mode: OFF (Set to manual)" "night_manual_off"
addCommand "Night mode: toggle automatic/manual" "toggle_auto"


## if there is no command, just print and exit
if [[ -z "$1" ]]; then
    printf '%s\n' "${TITLES[@]}"
    exit
fi


############ HELPER COMMANDS

function set_xrandr_only()
{
    selected=$1
    xrandr --output $selected --auto
    cmd="xrandr"
    for entry in "${ACTIVE_OUTPUTS[@]}"
    do
        if [ $selected != $entry ]; then
            cmd="$cmd --output $entry --off"
        fi
    done
    $cmd
}

function night_manual_on()
{
    ./night-mode-config set "manual"
}

function night_manual_off()
{
    ./night-mode-config set "off"
}

function toggle_auto()
{
    case `./night-mode-config` in
        on|auto|suntime) ./night-mode-config set "manual";;
        *) ./night-mode-config set "auto";;
    esac
}


$( ${COMMANDS[$1]} )
