#!/bin/bash
# Copyright (C) 2019 Omar Castro <omar.castro.360@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

BRIGHTNESS="$(cat $(ls /sys/class/backlight/*/brightness | head -n 1))"
MAX_BRIGHTNESS="$(cat $(ls /sys/class/backlight/*/max_brightness | head -n 1))"

max() {
   [ "$1" -gt "$2" ] && echo $1 || echo $2
}

echo "$(max $(($BRIGHTNESS - $MAX_BRIGHTNESS / 20)) 0)" | sudo tee /sys/class/backlight/intel_backlight/brightness
