#!/bin/bash
# Copyright (C) 2019 Omar Castro <omar.castro.360@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

DISPLAYINFO=$(xrandr --verbose \
    | grep -e "^[[:alpha:]]" -e '[[:alpha:]]*Gamma' -e '[[:alpha:]]*Brightness' \
    | grep -v "^Screen [0-9]" \
    | sed 's/^\s\s*/  /g' \
	| sed ':a;N;$!ba;s/\n  Brightness/|  Brightness/g' \
    | sed -r -e's/disconnected .*/disconnected/' -e 's/([0-9]+x[0-9]+\+[0-9]+\+[0-9]+).* ([0-9]*mm x [0-9]*mm)/\n  Resolution: \1|  Dimension:  \2/g' \
    | column -s"|" -t

)

OPTIONS=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && ./menu-actions  )

NIGHT_MODE="$(case `./night-mode-config` in
    on|auto|suntime ) echo "automatic";;
    manual ) echo "on (manual)";;
    off ) echo "off (manual)";;
esac)"

MESSAGE="$DISPLAYINFO"$'\n\n'"night mode: $NIGHT_MODE"$'\n\n'"Actions:"
WIDTH=$(( $(wc -L <<< "$MESSAGE"$'\n'"$OPTIONS") * 11 / 10 ))


ROFI_ARGS=(-dmenu -mesg "$MESSAGE" -eh 1 -width -$WIDTH)
if ! [[ -z "$rofi_theme" ]]; then
  ROFI_ARGS+=( -theme "$rofi_theme" )
fi
if ! [[ -z "$rofi_window_anchor" ]]; then
  ROFI_ARGS+=( -m -3 -theme-str '#window {anchor:'"$rofi_window_anchor"';}' )
fi


SELECTED_OPTION="$(rofi "${ROFI_ARGS[@]}" <<< "$OPTIONS" )"   

( cd "$( dirname "${BASH_SOURCE[0]}" )" && ./menu-actions "$SELECTED_OPTION" )


