#!/bin/env bash
# Copyright (C) 2019 Omar Castro <omar.castro.360@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

max() {
   [ "$1" -gt "$2" ] && echo $1 || echo $2
}

backlight_folder="$(ls -d /sys/class/backlight/* | head -n 1)"
if [ -d "$backlight_folder" ]; then
   BRIGHTNESS="$(cat $backlight_folder/brightness)"
   MAX_BRIGHTNESS="$(cat $backlight_folder/max_brightness | head -n 1)"
   echo "$(max $(($BRIGHTNESS - $MAX_BRIGHTNESS / 20)) 0)" > /sys/class/backlight/intel_backlight/brightness
fi
