#!/bin/bash
# Copyright (C) 2019 Omar Castro <omar.castro.360@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

CONFIG_DIR="$HOME/.config/i3blocklet-randr-backlight"
if [ ! -f $CONFIG_DIR/night_mode ]; then
	mkdir -p $CONFIG_DIR
	echo "off" > $CONFIG_DIR/night_mode
fi

case "$1" in
	set ) 
		case "$2" in
			on|auto|sunset|off|manual ) echo "$2" > $CONFIG_DIR/night_mode;;
			*) echo "error: invalid value use on of the following: on,auto,sunset,off,manual"
		esac;;
	get-config-file ) echo "$CONFIG_DIR/night_mode" ;;
	*) cat $CONFIG_DIR/night_mode
esac	