#!/bin/bash
# Copyright (C) 2019 Omar Castro <omar.castro.360@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.



BRIGHTNESS_FILE="$(ls /sys/class/backlight/*/brightness | head -n 1)"

handle_buttons(){
	case "$1" in
		1) "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && ./mouse-left-click && ./update-night-mode )" > /dev/null ;;
		4) "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && ./mouse-wheel-up )" > /dev/null ;;
		5) "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && ./mouse-wheel-down )" > /dev/null ;;
 		*) "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && ./update-night-mode )" > /dev/null ;;
  	esac
}

printBlock(){
	BRIGHTNESS="$(cat $BRIGHTNESS_FILE)"
	MAX_BRIGHTNESS="$(cat $(ls /sys/class/backlight/*/max_brightness | head -n 1))"
	let "RESULT =  $BRIGHTNESS * 100 / $MAX_BRIGHTNESS"
	echo "$RESULT"
}

case "$interval" in
	-3|persist )
		printBlock
		inotifywait -m -e close_write "$BRIGHTNESS_FILE" | while read; do printBlock; done &
		while read button; do handle_buttons $button; done
		;;
	* )
		handle_buttons $BLOCK_BUTTON
		printBlock
esac

