#!/bin/bash
# Copyright (C) 2019 Omar Castro <omar.castro.360@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

cd $( dirname "${BASH_SOURCE[0]}" )

function set_mode(){
	MONITORS=( $( xrandr | awk '/[0-9]+x[0-9]+\+[0-9]+\+[0-9]+/ && ( $2 == "connected" ){ print $1 }' ) )
	NUM_MONITORS=${#MONITORS[@]}
	cmd="xrandr "

    for entry in "${MONITORS[@]}"; do
        cmd="$cmd --output $entry --gamma $1 --brightness $2"
    done
    $cmd
}

case `./night-mode` in
	on|auto|suntime )
		night_xrandr_gamma=${night_gamma:-1.1:0.8:0.6}
		night_xrandr_brightness=${night_brightness:-0.7}
		TIMEZONE=$(timedatectl status | grep "zone" | sed -e 's/^[ ]*Time zone: \(.*\) (.*)$/\1/g')
		GEOLOCATION_COORDS=$(grep "$TIMEZONE" /usr/share/zoneinfo/zone.tab | awk '{print $2}')
		TIME=$(printf '%(%H:%M)T\n')
		VALS=( $( python_scripts/gamma_and_brightness_by_sun_time -c="$GEOLOCATION_COORDS" -g="$night_xrandr_gamma" -b="$night_xrandr_brightness") )
		set_mode "${VALS[@]}"
	;;
esac
