#!/bin/bash
# Copyright (C) 2019 Omar Castro <omar.castro.360@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

function set_mode(){
	XRANDR=$(which xrandr)
	MONITORS=( $( ${XRANDR} | awk '/[0-9]+x[0-9]+\+[0-9]+\+[0-9]+/ && ( $2 == "connected" ){ print $1 }' ) )
	NUM_MONITORS=${#MONITORS[@]}

	 cmd="xrandr "

    for entry in "${MONITORS[@]}"; do
        cmd="$cmd --output $entry --gamma $1 --brightness $2"
    done
    $cmd > /dev/null
}

. "$( dirname "${BASH_SOURCE[0]}" )"/state.conf
if [ "$AUTO_NIGHT_MODE" = 'ON' ]; then
	night_xrandr_gamma=${night_gamma:-1.1:0.8:0.7}
	night_xrandr_brightness=${night_brightness:-0.7}
	TIMEZONE=$(timedatectl status | grep "zone" | sed -e 's/^[ ]*Time zone: \(.*\) (.*)$/\1/g')
	TIME=$(printf '%(%H:%M)T\n')
	case $TIME in
		19*|2*|01*|02*|03*|04*|05*|06*) set_mode $night_xrandr_gamma $night_xrandr_brightness;;
		07*|08*|17*|18*) set_mode 1.05:0.875:0.8 0.8;;
		09*|16*) set_mode 1.0:0.95:0.9 0.9;;
		10*|11*|12*|13*|14*|15*) set_mode 1:1:1 1.0;;
	esac

fi